events {}

http {
    upstream menu_service {
        server menuservice_1:8084;
        # If later you scale:
        server menuservice_2:8084;
        server menuservice_3:8084;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://menu_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}