spring:
  application:
    name: CheckoutService
  jmx:
    enabled: false

server:
  port: 8089

services:
  menu:
    url: ${MENU_SERVICE_URL:http://localhost:8084}
  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8085}
  reservation:
    url: ${RESERVATION_SERVICE_URL:http://localhost:8086}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
    jmx:
      exposure:
        exclude: "*"
